### ISSUE TITLE
Country Flag and Name not diplayed, but [object object]

### ISSUE THREAD

**Issue by StephanTexxpro** [nlemoine/acf-country#32] opened 2020-07-12 09:44 UTC
Details
-------

 - WordPress version: 5.4.2
 - PHP version: 7.4.3
 - ACF version: 5.8.12 Pro
 - For UX/UI issues: Windows 10, Chrome 83.0.4103.97 (Offizieller Build) (64-Bit)
 - Allow null: true
 - Multiple values: false
 - Stylised UI: true (if this means select2?)
 - Condtional logic: false
 - Rules: none

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

Drop down selection is working as expected, so does saving the selected country. But the flags and the country names only show up in the dropdown, the field itself after selection only outputs as [obejct object]. This happens in the backend and in the frontend. 

### Steps to reproduce

Please see summary.

### First ideas 

Disabeling select2 in the field setting seems to fix the problem in a way that at leat the name of the country is displayed correctly. 
So seems to be related to select2, In Use: select2.full.min.js, 4.0.10.

**Comment by teemu-r** [comment] 2020-08-28 13:25
Any news about this? Same issue here.

**Comment by nlemoine** [comment] 2020-09-17 15:07
Hi @teemu-r and @StephanTexxpro 

I can't reproduce the bug. Tested with the exact same version you mentionned. 

Can you check again? ACF Pro 5.8.12 is loading Select2 4.0.3, not 4.0.10. 

Try to open devtools and check "disable cache" to be sure to get the latest versions of assets.

**Comment by nlemoine** [comment] 2020-09-17 15:20
The tag was targeting the wrong commit. This now fixed. Please download 2.0.2 again and test it, it should be fine now.

**Comment by emendelski** [comment] 2020-09-17 15:25
@nlemoine everything works great now! Thank you!

**Closed as completed** 2020-09-17 15:26 UTC
Labels: waiting feedback
