### ISSUE TITLE
Countries displaying as '[object Object]' after being selected 

### ISSUE THREAD

**Issue by dontdomilk** [nlemoine/acf-country#29] opened 2020-06-11 11:25 UTC
Details
-------

 - WordPress version: 5.4.2
 - ACF version: 5.8.12 (Pro)
 - For UX/UI issues: Mac, Chrome 83.0.4103.97
- Multiple: False

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### Bug summary

In the CMS, the selection shows '[object Object]' rather than the  selected country. It looks fine in the dropdown menu when  opened.

### Actual result

[object Object]

### Expected result

The select field would display the current selection
![Screen Shot 2020-06-11 at 14 24 55](https://user-images.githubusercontent.com/20464909/84379985-5a601080-abef-11ea-8408-44358e558cc7.png)
![Screen Shot 2020-06-11 at 14 24 25](https://user-images.githubusercontent.com/20464909/84379992-5e8c2e00-abef-11ea-9c8f-009542a3d042.png)

**Comment by johannesdb** [comment] 2020-06-12 17:08
I can confirm this bug. It is related to ACF 5.8.12. In ACF 5.8.11 the bug is not there

**Comment by vayurobins** [comment] 2020-06-17 12:42
I can also confirm this issue on two separate websites. Happened recently after updating.

**Comment by nlemoine** [comment] 2020-06-17 13:01
Thanks all for your feedback. I'm very busy at work right now and I don't know when I will have the time to solve this. If anyone can investigate, PR are welcome.

**Comment by vayurobins** [comment] 2020-06-17 22:13
I've fixed the issue:
in file acf-country.js
```
function format_country(state) {
	if (!state.id) {
		return state.text;
	}
	return '<span class="acf-country-flag-icon famfamfam-flags ' +
			state.id.toLowerCase() +
			'"></span> <span class="acf-country-flag-name">' +
			state.text +
			'</span>';
}
```
@nlemoine could you please add this?

**Comment by nlemoine** [comment] 2020-06-25 12:04
Thanks @vayurobins, the issue is now fixed.

**Closed as completed** 2020-06-25 12:03 UTC

**Comment by shmuelios** [comment] 2021-06-30 13:11
Unfortunately this field for me this field now exports the html.
e.g.` "<span class="acf-country-flag-icon famfamfam-flags ye"></span> <span class="acf-country-flag-name">Yemen</span>"`

I tried reverting the change to just check and it shows the [object Object] again.

anyone else having this issue?
